name: Deploy to GitHub Pages

# Define the permissions for the workflow
permissions:
  contents: write  # Grants write access to the contents of the repository
  pages: write    # Grants write access to GitHub Pages

on:
  push:
    branches:
      - master  # Change to your default branch, e.g., 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Copy Main_analyses.html to index.html
      - name: Copy Main_analyses.html to index.html
        run: |
          cp Main_analyses.html index.html  # Adjust if file is in a subfolder

      # Step 3: Set up Git user (to avoid permission issues)
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Step 4: Deploy to GitHub Pages using the GITHUB_TOKEN
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # The branch GitHub Pages uses
          folder: .
