name: Deploy to GitHub Pages

permissions:
  contents: write  # Grants write access to the contents of the repository
  pages: write    # Grants write access to GitHub Pages

on:
  push:
    branches:
      - master  # Change to your default branch, which is 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Verify the file exists before copying (Debugging)
      - name: Verify Main_analyses.html exists
        run: |
          ls -la  # List files to verify the location of Main_analyses.html
          cat Main_analyses.html  # Display the contents to ensure it is there

      # Step 3: Copy Main_analyses.html to index.html
      - name: Copy Main_analyses.html to index.html
        run: |
          cp Main_analyses.html index.html  # Adjust if file is in a subfolder
          ls -la  # Verify index.html is created after the copy

      # Step 4: Set up Git user (to avoid permission issues)
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Step 5: Commit the changes to the same branch (master)
      - name: Commit and push index.html
        run: |
          git add index.html
          git commit -m "Deploy index.html to GitHub Pages"
          git push origin master  # Push to the same branch

      # Step 6: Deploy to GitHub Pages using the GITHUB_TOKEN
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master  # Use the same branch you're pushing to
          folder: .
